[package]
name = "kinto_integrity"
version = "0.1.0"
authors = ["Christopher Henderson <chris@chenderson.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
crossbeam = "0.7.1"
tempdir = "0.3.7"
rand = "0.7.0"
lazy_static = "1.3.0"
bzip2 = "0.3.2"
tar = "0.4"
url = "2.1.0"
fern = "0.5.8"
log = "0.4"
chrono = "0.4.7"
hex = "0.3.2"
x509-parser = { path = "x509-parser" }
csv = "1.1"
serde_json = "1.0"
serde =  { version = "1.0.92", features = ["derive"] }
indicatif = "0.11.0"
sha2 = "0.8.1"
tempfile = "3.1.0"
rayon = "1.3.0"

# deps from Dana's tool
base64 = "0.10"
lmdb-rkv = "0.12.3"
rkv = { git = "https://github.com/mozilla/rkv", rev="6a866fdad2ca880df9b87fcbc9921abac1e91914", default-features = false }